### ISSUE TITLE
snapshot2 folder does not have BSC addresses

### ISSUE THREAD

**Issue by mendesbarreto** [Popsicle-Finance/airdrop#1]
Hello guys!

I tried to find my BSC address on the snapshot2 folder, but the Binance SmartChain JSON is missing. 

Could you please take a look? or only users from Phantom will receive this time?  

Thx

**Comment by mendesbarreto** [comment]
This file not exists:

https://github.com/Popsicle-Finance/airdrop/blob/24ac1a42f9b200e530afe0e3934d0b637eb07341/unused_helper/intersection.js#L6

**Comment by Yahdi14** [comment]
0xf6dFd677c4fED4FAdbd1f254C3346F72169341f6
